// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmOlRoDRQAnSKERjZNunB0gVxW8__yzOU',
    appId: '1:858989998310:web:c81424e274b4c06f1f8b27',
    messagingSenderId: '858989998310',
    projectId: 'chatapp-9ad29',
    authDomain: 'chatapp-9ad29.firebaseapp.com',
    storageBucket: 'chatapp-9ad29.firebasestorage.app',
    measurementId: 'G-DQJ6QGPTBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA39wHfr8SPWZtP7Dv0mg-S80z-prqYgDw',
    appId: '1:858989998310:android:325d2c01caa1291c1f8b27',
    messagingSenderId: '858989998310',
    projectId: 'chatapp-9ad29',
    storageBucket: 'chatapp-9ad29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk9Xqz-FV9DldEdRo-WNU-WMoI-90OtxA',
    appId: '1:858989998310:ios:47c6a3314c72d8fa1f8b27',
    messagingSenderId: '858989998310',
    projectId: 'chatapp-9ad29',
    storageBucket: 'chatapp-9ad29.firebasestorage.app',
    androidClientId: '858989998310-ke8bqcdvnskjn834rscug2idhq6pk26v.apps.googleusercontent.com',
    iosClientId: '858989998310-3f31u8mv85qhicpb4c2igdsre6cs7g3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.adiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk9Xqz-FV9DldEdRo-WNU-WMoI-90OtxA',
    appId: '1:858989998310:ios:47c6a3314c72d8fa1f8b27',
    messagingSenderId: '858989998310',
    projectId: 'chatapp-9ad29',
    storageBucket: 'chatapp-9ad29.firebasestorage.app',
    iosBundleId: 'com.example.adiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmOlRoDRQAnSKERjZNunB0gVxW8__yzOU',
    appId: '1:858989998310:web:7cb5c13744e693c11f8b27',
    messagingSenderId: '858989998310',
    projectId: 'chatapp-9ad29',
    authDomain: 'chatapp-9ad29.firebaseapp.com',
    storageBucket: 'chatapp-9ad29.firebasestorage.app',
    measurementId: 'G-BNX7JCZPEV',
  );
}